const byId = <T extends HTMLElement>(id: string): T | null => document.getElementById(id) as T | null;

export const refs = {
  input: byId<HTMLInputElement>('message-input'),
  addButton: byId<HTMLButtonElement>('add-button'),
  tasksList: byId<HTMLDivElement>('tasks-list'),
  emptyState: byId<HTMLDivElement>('empty-state'),
  overlay: byId<HTMLDivElement>('edit-overlay'),
  editInput: byId<HTMLInputElement>('edit-input'),
  editDoneInput: byId<HTMLInputElement>('edit-done'),
  editDetailsInput: byId<HTMLTextAreaElement>('edit-details'),
  cancelEditBtn: byId<HTMLButtonElement>('cancel-edit'),
  saveEditBtn: byId<HTMLButtonElement>('save-edit'),
  listsList: byId<HTMLDivElement>('lists-list'),
  listsEmpty: byId<HTMLDivElement>('lists-empty'),
  listsToggle: byId<HTMLButtonElement>('lists-toggle'),
  addListBtn: byId<HTMLButtonElement>('add-list-button'),
  listOverlay: byId<HTMLDivElement>('list-overlay'),
  listInput: byId<HTMLInputElement>('list-input'),
  cancelListBtn: byId<HTMLButtonElement>('cancel-list'),
  saveListBtn: byId<HTMLButtonElement>('save-list'),
  addTaskListPicker: byId<HTMLButtonElement>('add-task-list-picker'),
  addTaskListMenu: byId<HTMLDivElement>('add-task-list-menu'),
  addTaskListLabel: byId<HTMLSpanElement>('add-task-list-label'),
  listsSearchInput: byId<HTMLInputElement>('lists-search-input'),
  listsSearchClear: byId<HTMLButtonElement>('lists-search-clear'),
  modalListPicker: byId<HTMLButtonElement>('modal-list-picker'),
  modalListMenu: byId<HTMLDivElement>('modal-list-menu'),
  modalListLabel: byId<HTMLSpanElement>('modal-list-label'),
  priorityPicker: byId<HTMLButtonElement>('priority-picker'),
  priorityMenu: byId<HTMLDivElement>('priority-menu'),
  priorityChip: byId<HTMLSpanElement>('priority-chip'),
  priorityLabel: byId<HTMLSpanElement>('priority-label'),
  reminderPicker: byId<HTMLButtonElement>('reminder-picker'),
  reminderMenu: byId<HTMLDivElement>('reminder-menu'),
  reminderLabel: byId<HTMLSpanElement>('reminder-label'),
  reminderDateInput: byId<HTMLInputElement>('reminder-date'),
  reminderTimeInput: byId<HTMLInputElement>('reminder-time'),
  reminderTimeOptions: byId<HTMLDataListElement>('reminder-time-options'),
  repeatPicker: byId<HTMLButtonElement>('repeat-picker'),
  repeatMenu: byId<HTMLDivElement>('repeat-menu'),
  repeatLabel: byId<HTMLSpanElement>('repeat-label'),
  repeatOverlay: byId<HTMLDivElement>('repeat-overlay'),
  repeatStartDate: byId<HTMLInputElement>('repeat-start-date'),
  repeatTypeSelect: byId<HTMLSelectElement>('repeat-type'),
  repeatIntervalSelect: byId<HTMLSelectElement>('repeat-interval'),
  repeatIntervalUnit: byId<HTMLSpanElement>('repeat-interval-unit'),
  repeatWeeklyOptions: byId<HTMLDivElement>('repeat-weekly-options'),
  repeatWeekdays: byId<HTMLDivElement>('repeat-weekdays'),
  repeatMonthlyOptions: byId<HTMLDivElement>('repeat-monthly-options'),
  repeatMonthlyDay: byId<HTMLSelectElement>('repeat-monthly-day'),
  repeatMonthlyOrdinal: byId<HTMLSelectElement>('repeat-monthly-ordinal'),
  repeatMonthlyWeekday: byId<HTMLSelectElement>('repeat-monthly-weekday'),
  repeatYearlyOptions: byId<HTMLDivElement>('repeat-yearly-options'),
  repeatYearlyMonth: byId<HTMLSelectElement>('repeat-yearly-month'),
  repeatYearlyDay: byId<HTMLSelectElement>('repeat-yearly-day'),
  repeatYearlyOrdinal: byId<HTMLSelectElement>('repeat-yearly-ordinal'),
  repeatYearlyWeekday: byId<HTMLSelectElement>('repeat-yearly-weekday'),
  repeatEndType: byId<HTMLSelectElement>('repeat-end-type'),
  repeatEndDate: byId<HTMLInputElement>('repeat-end-date'),
  repeatEndCount: byId<HTMLInputElement>('repeat-end-count'),
  repeatEndOccurrences: byId<HTMLSpanElement>('repeat-end-occurrences'),
  repeatSummary: byId<HTMLDivElement>('repeat-summary'),
  repeatCancel: byId<HTMLButtonElement>('cancel-repeat'),
  repeatSave: byId<HTMLButtonElement>('save-repeat'),
  settingsOverlay: byId<HTMLDivElement>('settings-overlay'),
  settingsRadio12: byId<HTMLInputElement>('time-12'),
  settingsRadio24: byId<HTMLInputElement>('time-24'),
  settingsSave: byId<HTMLButtonElement>('save-settings'),
  settingsCancel: byId<HTMLButtonElement>('cancel-settings'),
  dateFormatSelect: byId<HTMLSelectElement>('date-format'),
  tasksTitleEl: document.querySelector<HTMLParagraphElement>('.tasks-title'),
};

export const dropIndicator = (() => {
  const el = document.createElement('div');
  el.className = 'drop-indicator';
  return el;
})();

export const listDropIndicator = (() => {
  const el = document.createElement('div');
  el.className = 'list-drop-indicator';
  return el;
})();
