const byId = <T extends HTMLElement>(id: string): T | null => document.getElementById(id) as T | null;

export const refs = {
  input: byId<HTMLInputElement>('message-input'),
  addButton: byId<HTMLButtonElement>('add-button'),
  tasksList: byId<HTMLDivElement>('tasks-list'),
  emptyState: byId<HTMLDivElement>('empty-state'),
  overlay: byId<HTMLDivElement>('edit-overlay'),
  editInput: byId<HTMLInputElement>('edit-input'),
  editDoneInput: byId<HTMLInputElement>('edit-done'),
  editDetailsInput: byId<HTMLTextAreaElement>('edit-details'),
  cancelEditBtn: byId<HTMLButtonElement>('cancel-edit'),
  saveEditBtn: byId<HTMLButtonElement>('save-edit'),
  listsList: byId<HTMLDivElement>('lists-list'),
  listsEmpty: byId<HTMLDivElement>('lists-empty'),
  listsToggle: byId<HTMLButtonElement>('lists-toggle'),
  addListBtn: byId<HTMLButtonElement>('add-list-button'),
  listOverlay: byId<HTMLDivElement>('list-overlay'),
  listInput: byId<HTMLInputElement>('list-input'),
  cancelListBtn: byId<HTMLButtonElement>('cancel-list'),
  saveListBtn: byId<HTMLButtonElement>('save-list'),
  viewPicker: byId<HTMLButtonElement>('view-picker'),
  viewMenu: byId<HTMLDivElement>('view-menu'),
  viewLabel: byId<HTMLSpanElement>('view-label'),
  viewCount: byId<HTMLSpanElement>('view-count'),
  viewEdited: byId<HTMLSpanElement>('view-edited'),
  viewBarNaming: byId<HTMLDivElement>('view-bar-naming'),
  viewBarActions: byId<HTMLDivElement>('view-bar-actions'),
  listsSearchInput: byId<HTMLInputElement>('lists-search-input'),
  listsSearchClear: byId<HTMLButtonElement>('lists-search-clear'),
  searchModeSimple: byId<HTMLInputElement>('search-mode-simple'),
  searchModeAdvanced: byId<HTMLInputElement>('search-mode-advanced'),
  searchStaleNote: byId<HTMLSpanElement>('search-stale-note'),
  searchStatusLine: byId<HTMLDivElement>('search-status-line'),
  searchStatusLive: byId<HTMLSpanElement>('search-status-live'),
  searchHelpBtn: byId<HTMLButtonElement>('search-help-btn'),
  searchHelpPopover: byId<HTMLDivElement>('search-help-popover'),
  searchHelpSimple: byId<HTMLDivElement>('search-help-simple'),
  searchHelpAdvanced: byId<HTMLDivElement>('search-help-advanced'),
  querySuggestMenu: byId<HTMLDivElement>('query-suggest-menu'),
  modalListPicker: byId<HTMLButtonElement>('modal-list-picker'),
  modalListMenu: byId<HTMLDivElement>('modal-list-menu'),
  modalListLabel: byId<HTMLSpanElement>('modal-list-label'),
  tagsList: byId<HTMLDivElement>('tags-list'),
  tagsEmpty: byId<HTMLDivElement>('tags-empty'),
  tagsToggle: byId<HTMLButtonElement>('tags-toggle'),
  tagOverlay: byId<HTMLDivElement>('tag-overlay'),
  tagInput: byId<HTMLInputElement>('tag-input'),
  tagColorSwatches: byId<HTMLDivElement>('tag-color-swatches'),
  cancelTagBtn: byId<HTMLButtonElement>('cancel-tag'),
  saveTagBtn: byId<HTMLButtonElement>('save-tag'),
  tagsPicker: byId<HTMLButtonElement>('tags-picker'),
  tagsMenu: byId<HTMLDivElement>('tags-menu'),
  tagsMenuList: byId<HTMLDivElement>('tags-menu-list'),
  tagsMenuNew: byId<HTMLInputElement>('tags-menu-new'),
  tagsLabel: byId<HTMLSpanElement>('tags-label'),
  tagSuggestMenu: byId<HTMLDivElement>('tag-suggest-menu'),
  addTaskTags: byId<HTMLDivElement>('add-task-tags'),
  tagFilterChip: byId<HTMLButtonElement>('tag-filter-chip'),
  smartListsList: byId<HTMLDivElement>('smart-lists-list'),
  smartListsEmpty: byId<HTMLDivElement>('smart-lists-empty'),
  smartListsToggle: byId<HTMLButtonElement>('smart-lists-toggle'),
  addSmartListBtn: byId<HTMLButtonElement>('add-smart-list-button'),
  smartListOverlay: byId<HTMLDivElement>('smart-list-overlay'),
  smartListModalTitle: byId<HTMLHeadingElement>('smart-list-modal-title'),
  smartListNameInput: byId<HTMLInputElement>('smart-list-name-input'),
  smartListQueryInput: byId<HTMLTextAreaElement>('smart-list-query-input'),
  smartListModalError: byId<HTMLParagraphElement>('smart-list-modal-error'),
  cancelSmartListBtn: byId<HTMLButtonElement>('cancel-smart-list'),
  saveSmartListBtn: byId<HTMLButtonElement>('save-smart-list'),
  addTaskTemplate: byId<HTMLDivElement>('add-task-template'),
  priorityPicker: byId<HTMLButtonElement>('priority-picker'),
  priorityMenu: byId<HTMLDivElement>('priority-menu'),
  priorityChip: byId<HTMLSpanElement>('priority-chip'),
  priorityLabel: byId<HTMLSpanElement>('priority-label'),
  reminderPicker: byId<HTMLButtonElement>('reminder-picker'),
  reminderMenu: byId<HTMLDivElement>('reminder-menu'),
  reminderLabel: byId<HTMLSpanElement>('reminder-label'),
  reminderDateInput: byId<HTMLInputElement>('reminder-date'),
  reminderTimeInput: byId<HTMLInputElement>('reminder-time'),
  reminderTimeOptions: byId<HTMLDataListElement>('reminder-time-options'),
  repeatPicker: byId<HTMLButtonElement>('repeat-picker'),
  repeatMenu: byId<HTMLDivElement>('repeat-menu'),
  repeatLabel: byId<HTMLSpanElement>('repeat-label'),
  repeatOverlay: byId<HTMLDivElement>('repeat-overlay'),
  repeatStartDate: byId<HTMLInputElement>('repeat-start-date'),
  repeatTypeSelect: byId<HTMLSelectElement>('repeat-type'),
  repeatIntervalSelect: byId<HTMLSelectElement>('repeat-interval'),
  repeatIntervalUnit: byId<HTMLSpanElement>('repeat-interval-unit'),
  repeatWeeklyOptions: byId<HTMLDivElement>('repeat-weekly-options'),
  repeatWeekdays: byId<HTMLDivElement>('repeat-weekdays'),
  repeatMonthlyOptions: byId<HTMLDivElement>('repeat-monthly-options'),
  repeatMonthlyDay: byId<HTMLSelectElement>('repeat-monthly-day'),
  repeatMonthlyOrdinal: byId<HTMLSelectElement>('repeat-monthly-ordinal'),
  repeatMonthlyWeekday: byId<HTMLSelectElement>('repeat-monthly-weekday'),
  repeatYearlyOptions: byId<HTMLDivElement>('repeat-yearly-options'),
  repeatYearlyMonth: byId<HTMLSelectElement>('repeat-yearly-month'),
  repeatYearlyDay: byId<HTMLSelectElement>('repeat-yearly-day'),
  repeatYearlyOrdinal: byId<HTMLSelectElement>('repeat-yearly-ordinal'),
  repeatYearlyWeekday: byId<HTMLSelectElement>('repeat-yearly-weekday'),
  repeatEndType: byId<HTMLSelectElement>('repeat-end-type'),
  repeatEndDate: byId<HTMLInputElement>('repeat-end-date'),
  repeatEndCount: byId<HTMLInputElement>('repeat-end-count'),
  repeatEndOccurrences: byId<HTMLSpanElement>('repeat-end-occurrences'),
  repeatSummary: byId<HTMLDivElement>('repeat-summary'),
  repeatCancel: byId<HTMLButtonElement>('cancel-repeat'),
  repeatSave: byId<HTMLButtonElement>('save-repeat'),
  settingsOverlay: byId<HTMLDivElement>('settings-overlay'),
  settingsRadio12: byId<HTMLInputElement>('time-12'),
  settingsRadio24: byId<HTMLInputElement>('time-24'),
  settingsThemeSystem: byId<HTMLInputElement>('theme-system'),
  settingsThemeLight: byId<HTMLInputElement>('theme-light'),
  settingsThemeDark: byId<HTMLInputElement>('theme-dark'),
  settingsSave: byId<HTMLButtonElement>('save-settings'),
  settingsCancel: byId<HTMLButtonElement>('cancel-settings'),
  dateFormatSelect: byId<HTMLSelectElement>('date-format'),
  tagColorsCheckbox: byId<HTMLInputElement>('tag-colors'),
  shortcutList: byId<HTMLDivElement>('shortcut-list'),
  shortcutError: byId<HTMLParagraphElement>('shortcut-error'),
  resetShortcuts: byId<HTMLButtonElement>('reset-shortcuts'),
  shortcutsOverlay: byId<HTMLDivElement>('shortcuts-overlay'),
  shortcutsBody: byId<HTMLDivElement>('shortcuts-body'),
  shortcutsClose: byId<HTMLButtonElement>('close-shortcuts'),
};

export const dropIndicator = (() => {
  const el = document.createElement('div');
  el.className = 'drop-indicator';
  return el;
})();

export const listDropIndicator = (() => {
  const el = document.createElement('div');
  el.className = 'list-drop-indicator';
  return el;
})();
